### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by MasterIfeanyi** [MasterIfeanyi/Rwanda#2]
I would love a well-detailed readme for this project. The readme should follow the same pattern as this github [readme](https://github.com/MasterIfeanyi/ifeanyi-advice)

**Comment by Zainab-ik** [comment]
I'd love to contribute to this project.

**Comment by Zainab-ik** [comment]
I've sent a pull request

**Comment by MasterIfeanyi** [comment]
No, that will be all. Thank you once again.
